nome = str(input('Qual o seu nome completo?')).strip()
print('analisando o seu nome...')
print(' seu nome em maiúsculas é {}'.format(nome.upper()))
print(' seu nome em minúsculas é {}'.format(nome.lower()))
print('seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
print('o primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))